version: '3.9'

services:
  app:
    build: .
    container_name: url-shortener-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/url-shortener
    depends_on:
      - mongo
    volumes:
      - .:/app           # Host klasörünü container içine bağla
      - /app/node_modules  # Node_modules container içinde ayrı kalsın
    command: npm run dev   # Geliştirme modunda çalıştır

  mongo:
    image: mongo:6.0
    container_name: url-shortener-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
